const CART_ADD_ITEM = 'CART_ADD_ITEM'
const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADRESS'
const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

const ActionTypes = {
  CART_ADD_ITEM,
  CART_REMOVE_ITEM,
  CART_SAVE_SHIPPING_ADDRESS,
  CART_SAVE_PAYMENT_METHOD,
}

export default ActionTypes
